### ISSUE TITLE
NameError when using train-adaptive-nets

### ISSUE THREAD

**Issue by CloudApiStudy** [MasonMcGill/multipath-nn#1]
I'm trying to run an experiment with `python3 train-adaptive-nets hybrid-cr-tree-dynkcpt`, and there's error which doesn't occur in `train-nets` experiments.

I'm using tensorflow-gpu==1.12, numpy==1.15.4, matplotlib==3.0.3, seaborn==0.9.0, scipy==1.2.1

The error log goes as follows:
```
Traceback (most recent call last):
  File "train-adaptive-nets", line 118, in <module>
    train_net()
  File "train-adaptive-nets", line 96, in train_net
    net = expt.net(dataset.x0_shape, dataset.y_shape)
  File "/home/cc/multipath-nn/scripts/arch_and_hypers.py", line 112, in make_net
    layers_3_through_7(),
  File "/home/cc/multipath-nn/scripts/arch_and_hypers.py", line 102, in layers_3_through_7
    rcm(3, reg(y_shape[0]),
NameError: name 'y_shape' is not defined
```

Looking forward to your rely.

**Comment by CloudApiStudy** [comment]
I manually changed the the input params of `layers_3_through_7()` and solved the above problem. There just come out a new one.

```
2019-03-04 04:01:28.134054: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 16384 and 1. Shapes are [?,16384] and [?,1].
        From merging shape 0 with other shapes. for 'concat/concat_dim' (op: 'Pack') with input shapes: [?,16384], [?,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train-adaptive-nets", line 122, in <module>
    train_net()
  File "train-adaptive-nets", line 100, in train_net
    net = expt.net(dataset.x0_shape, dataset.y_shape)
  File "/home/cc/multipath-nn/scripts/arch_and_hypers.py", line 126, in make_net
    root=root, **hypers)
  File "/home/cc/multipath-nn/scripts/lib/net_types.py", line 54, in __init__
    self.link()
  File "/home/cc/multipath-nn/scripts/lib/net_types.py", line 272, in link
    link_layer(self.root, self.x0, self.y, self.mode)
  File "/home/cc/multipath-nn/scripts/lib/net_types.py", line 271, in link_layer
    link_layer(s, ℓ.x, y, mode)
  File "/home/cc/multipath-nn/scripts/lib/net_types.py", line 266, in link_layer
    x_rte = list(map(concat_k_cpt, ℓ.x))
  File "/home/cc/multipath-nn/scripts/lib/net_types.py", line 262, in <lambda>
    * tf.ones((tf.shape(x_)[0], 1))])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1121, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 971, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 923, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 4875, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 16384 and 1. Shapes are [?,16384] and [?,1].
        From merging shape 0 with other shapes. for 'concat/concat_dim' (op: 'Pack') with input shapes: [?,16384], [?,1].
```

**Comment by CloudApiStudy** [comment]
Solved. The concat API has changed the parameters order.
